blank_issues_enabled: true
version: 2.1
contact_links:
  - name: Reach out to vishwa.ai
    url: https://vishwa.ai
    about: For more information about idea and people behind this OSS project.
  - name: Vishwa Labs Discussions
    url: https://github.com/vishwa-labs/vishwa-ml-sdk/discussions
    about: Please ask general questions here.
  - name: Reachout to owner
    url: sharan@vishwa.tech
    about: Contact the maintainer for catchup or support
