{
 "title": "Langchain Observability Dashboard",
 "tags": [
  "langchain",
  "xpuls-labs",
  "xpuls.ai",
  "mlmonitor"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "agent_name", "label": "agent_name", "query": { "query": "label_values(agent_name)" } },
   {
    "name": "model_type",
    "label": "model_type",
    "query": {
     "query": "label_values(langchain_chain_execution_total{agent_name=\"$agent_name\"},ml_model_type)"
    }
   },
   {
    "name": "model_name",
    "label": "model_name",
    "query": {
     "query": "label_values(langchain_chain_execution_total{ml_model_type=\"$model_type\"},ml_model_name)"
    }
   },
   {
    "name": "tool_action",
    "label": "tool_action",
    "query": {
     "query": "label_values(langchain_tools_usage_total{agent_name=\"$agent_name\"},action)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Langchain - Agent: $agent_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Langchain - Chain Latency Distribution Past 1h",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(\n    100 * \n    increase(langchain_agent_run_latency_bucket{agent_name=\"$agent_name\"}[1h]) \n    / \n    scalar(sum(increase(langchain_agent_run_latency_bucket{agent_name=\"$agent_name\"}[1h])))\n)\n",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "Langchain - Agent Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(langchain_agent_run_latency_sum{agent_name=\"$agent_name\"}[1m])) / sum(rate(langchain_agent_run_latency_count{agent_name=\"$agent_name\"}[1m]))\n",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(langchain_agent_run_latency_bucket{agent_name=\"$agent_name\"}[1m])) by (le))\n",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(langchain_agent_run_latency_bucket{agent_name=\"$agent_name\"}[1m])) by (le))\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(langchain_agent_run_latency_bucket[1m])) by (le))\n",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Langchain - Chains", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Chain Executions Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(langchain_chain_execution_total{execution_step=\"on_chain_start\", agent_name=\"$agent_name\"}[1m])",
     "legendFormat": "{{ml_model_name}},{{ml_model_type}}"
    }
   ]
  },
  {
   "title": "Langchain - Chain Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(langchain_chain_latency_sum{ml_model_name=\"$model_name\", ml_model_type=\"$model_type\", agent_name=\"$agent_name\"}[1m])) / sum(rate(langchain_chain_latency_count{ml_model_name=\"$model_name\", ml_model_type=\"$model_type\", agent_name=\"$agent_name\"}[1m]))\n",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(langchain_chain_latency_bucket{ml_model_name=\"$model_name\", ml_model_type=\"$model_type\", agent_name=\"$agent_name\"}[1m])) by (le))\n",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(langchain_chain_latency_bucket{ml_model_name=\"$model_name\", ml_model_type=\"$model_type\", agent_name=\"$agent_name\"}[1m])) by (le))\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(langchain_chain_latency_bucket{ml_model_name=\"$model_name\", ml_model_type=\"$model_type\", agent_name=\"$agent_name\"}[1m])) by (le))\n",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Langchain - Chain Latency Distribution Past 3h",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(\n    100 * \n    increase(langchain_chain_latency_bucket{ml_model_type=\"$model_type\", ml_model_name=\"$model_name\", agent_name=\"$agent_name\"}[3h]) \n    / \n    scalar(sum(increase(langchain_chain_latency_bucket{ml_model_type=\"$model_type\", ml_model_name=\"$model_name\", agent_name=\"$agent_name\"}[3h])))\n)\n",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "Langchain - Chain Latency Distribution Past 1h",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(\n    100 * \n    increase(langchain_chain_latency_bucket{ml_model_type=\"$model_type\", ml_model_name=\"$model_name\", agent_name=\"$agent_name\"}[1h]) \n    / \n    scalar(sum(increase(langchain_chain_latency_bucket{ml_model_type=\"$model_type\", ml_model_name=\"$model_name\", agent_name=\"$agent_name\"}[1h])))\n)\n",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "Langchain Chain Usage past 1hr - Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(langchain_chain_execution_total{execution_step=\"on_chain_end\", agent_name=\"$agent_name\", ml_model_type=\"$model_type\", ml_model_name=\"$model_name\"}[1h])\n",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Langchain Chain Usage past 1hr - Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(langchain_chain_execution_total{execution_step=\"on_chain_error\", agent_name=\"$agent_name\", ml_model_type=\"$model_type\", ml_model_name=\"$model_name\"}[1h])\n",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  { "title": "Langchain - LLM Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "LLM Executions Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(langchain_chat_model_total{execution_step=\"on_llm_end\", agent_name=\"$agent_name\"}[1m])",
     "legendFormat": "{{ml_model_name}},{{ml_model_type}}"
    }
   ]
  },
  {
   "title": "Langchain - LLM Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(langchain_chat_model_latency_sum{ml_model_name=\"$model_name\", ml_model_type=\"$model_type\", agent_name=\"$agent_name\"}[1m])) / sum(rate(langchain_chat_model_latency_count{ml_model_name=\"$model_name\", ml_model_type=\"$model_type\", agent_name=\"$agent_name\"}[1m]))\n",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(langchain_chat_model_latency_bucket{ml_model_name=\"$model_name\", ml_model_type=\"$model_type\", agent_name=\"$agent_name\"}[1m])) by (le))\n",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(langchain_chat_model_latency_bucket{ml_model_name=\"$model_name\", ml_model_type=\"$model_type\", agent_name=\"$agent_name\"}[1m])) by (le))\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(langchain_chat_model_latency_bucket{ml_model_name=\"$model_name\", ml_model_type=\"$model_type\", agent_name=\"$agent_name\"}[1m])) by (le))\n",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Langchain - LLM Latency Distribution Past 3h",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(\n    100 * \n    increase(langchain_chat_model_latency_bucket{ml_model_type=\"$model_type\", ml_model_name=\"$model_name\", agent_name=\"$agent_name\"}[3h]) \n    / \n    scalar(sum(increase(langchain_chat_model_latency_bucket{ml_model_type=\"$model_type\", ml_model_name=\"$model_name\", agent_name=\"$agent_name\"}[3h])))\n)\n",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "Langchain - LLM Latency Distribution Past 3h",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(\n    100 * \n    increase(langchain_chat_model_latency_bucket{ml_model_type=\"$model_type\", ml_model_name=\"$model_name\", agent_name=\"$agent_name\"}[3h]) \n    / \n    scalar(sum(increase(langchain_chat_model_latency_bucket{ml_model_type=\"$model_type\", ml_model_name=\"$model_name\", agent_name=\"$agent_name\"}[3h])))\n)\n",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  { "title": "OpenAI - Tokens Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "OpenAI Tokens Used per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(langchain_llm_tokens_total{agent_name=\"$agent_name\", ml_model_name=\"$model_name\"}[1m])",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Tokens used in last 1hr - total_tokens",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(langchain_llm_tokens_total{agent_name=\"$agent_name\", ml_model_name=\"$model_name\", usage_type=\"total_tokens\"}[1h])",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Tokens used in last 1hr - completion_tokens",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(langchain_llm_tokens_total{agent_name=\"$agent_name\", ml_model_name=\"$model_name\", usage_type=\"completion_tokens\"}[1h])",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Tokens used in last 1hr - prompt_tokens",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(langchain_llm_tokens_total{agent_name=\"$agent_name\", ml_model_name=\"$model_name\", usage_type=\"prompt_tokens\"}[1h])",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  { "title": "Langchain - Tools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Langchain - Tool Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(langchain_tools_usage_total{agent_name=\"$agent_name\", execution_step=\"on_tool_start\"}[1m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Langchain - Tool Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(langchain_tool_latency_sum{agent_name=\"$agent_name\"}[1m])) / sum(rate(langchain_tool_latency_count{ agent_name=\"$agent_name\"}[1m]))\n",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(langchain_tool_latency_bucket{agent_name=\"$agent_name\"}[1m])) by (le))\n",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(langchain_tool_latency_bucket{agent_name=\"$agent_name\"}[1m])) by (le))\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(langchain_tool_latency_bucket{agent_name=\"$agent_name\"}[1m])) by (le))\n",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Langchain - LLM Latency Distribution Past 1h",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(\n    100 * \n    increase(langchain_tool_latency_bucket{agent_name=\"$agent_name\",action=\"$tool_action\"}[1h]) \n    / \n    scalar(sum(increase(langchain_tool_latency_bucket{agent_name=\"$agent_name\",action=\"$tool_action\"}[1h])))\n)\n",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "Langchain - LLM Latency Distribution Past 1h",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(\n    100 * \n    increase(langchain_tool_latency_bucket{agent_name=\"$agent_name\",action=\"$tool_action\"}[3h]) \n    / \n    scalar(sum(increase(langchain_tool_latency_bucket{agent_name=\"$agent_name\",action=\"$tool_action\"}[3h])))\n)\n",
     "legendFormat": "{{le}}s"
    }
   ]
  },
  {
   "title": "Tool Usage past 1hr - Success ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(langchain_tools_usage_total{execution_step=\"on_tool_end\", agent_name=\"$agent_name\", action=\"$tool_action\"}[1h])\n",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Tool Usage past 1hr - Errors ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(langchain_tools_usage_total{execution_step=\"on_tool_error\", agent_name=\"$agent_name\", action=\"$tool_action\"}[1h])\n",
     "legendFormat": "{{usage_type}}"
    }
   ]
  }
 ]
}